name: family-website
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: einsfliegen/family-website:latest
    ports:
      - "3100:3100"
      - "80:80"
      - "443:443"
    secrets:
      - family_website_secret
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - SSL_CERT=/etc/letsencrypt/live/einsfliegen.com/fullchain.pem
      - SSL_KEY=/etc/letsencrypt/live/einsfliegen.com/privkey.pem
    restart: unless-stopped
    working_dir: /app
    command: ["node", "app.js"]

secrets:
  family_website_secret:
    file: ./secrets.txt

# /etc/letsencrypt/live/einsfliegen.com/fullchain.pem
# /etc/letsencrypt/live/einsfliegen.com/privkey.pem

# To deploy the stack, use the command:
# docker stack deploy -c docker-compose.yml family-website